ngpus: 2    # GPU总数

train:
  train_mode: 'gpu' # 训练模式
  use_gpu: 1  # 使用第几个GPU
  workers: 2  # 用于数据加载的worker数量
  train_test_rate: 0.7
  lttb: 8     # 取值范围[5, 10] 
  preiod: 7   # 构建2D特征图的W
  epoch: 150
  batch_size: 64
  lr: 0.001
  loss_weight: [0.05, 0.95]
  lambda: 0.1
  tau: 0.07

model:
  layer_num: 2
  feature_dim: 64
  hidden_nc: 16
  kernel_size: [3,1]
  dropout: 0.1
  project_dim: 16
  classify_dim: 32
